apiVersion: v3
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: mynginx
  template:
    metadata:
    labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx-container
        image: maha4iac/mahalogin:1
        ports:
        - containerPort: 80