apiVersion: v2
kind: ReplicationController
metadata:
  name: mynginxrc
spec:
  replicas: 3
  selector:
    app: mynginx
  template:
    metadata:
    labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx-container
        image: nginx
        ports:
        - containerPort: 80